### ISSUE TITLE
Unwanted behavior in tables in Firefox introduced by the new canPropagate implementation

### ISSUE THREAD

**Issue by lukaszgo1** [ABuffEr/columnsReview#11]
To reproduce:

1. Open https://github.com/ABuffEr/columnsReview
2. Move to the first table
3. Press TAB to focus link called 'addon'
4. Try to perform say all at this point

Due to the fact that this link is inside a table  which gets `MozillaTable` in its MRO default NVDA's say all is not invoked and the columnsReview method is used which is obviously not what we want.

I've decided to create an issue rather than just open a PR since I don't know where `MozillaTable` is used as I'm not a Thunderbird user.  @ABuffEr Would it be acceptable to add it to MRO only for TB message list, or are there other places where it is useful for you?

**Comment by ABuffEr** [comment]
Hi,
I chose to mantain a possibility for other Mozilla-based applications (I'm sure in the past it was useful), so I limited re-classing to obj without treeInterceptor.
Try the just released build.

**Comment by lukaszgo1** [comment]
Thanks for an instant fix! The latest build seems to fix this issue for me.
