### ISSUE TITLE
Can I use NVDA's veep to report List tops and List bottoms?

### ISSUE THREAD

**Issue by Lo-lo78** [ABuffEr/columnsReview#26]
Hello Alberto and everyone.
Is it also possible to use NVDA's veep to announce list limits?
Obviously if they are announced with voice there is no veep and if there is veep there is no screen reader voice.
For those wishing to use it, it might be better to separate the speech synthesis thanks to the veep with the limits of the list.
Greetings.

Manolo

**Comment by ABuffEr** [comment]
Hi @Lo-lo78,
sure, I can introduce a combobox to choose between voice message and beep. But I'm not sure about frequency and duration for top and bottom beep, and I'd want sincerely to limit the GUI controls to add...

**Comment by Lo-lo78** [comment]
@ABuffEr 
The frequencies could be 900Hz for List top and 440Hz for List bottom and the length of the veep 100 milliseconds.
Of course if working with GUI controls is a problem try a combo box.
If you are not sure about hz and milli seconds in the future you might think about giving the user with edit fields the frequency for the List top and for the List bottom.
A third edit field for the duration of the veep in milliseconds.
Thank you!

**Comment by ABuffEr** [comment]
Hi @Lo-lo78,
I slightly changed your suggested values (900 seems too acute in headphones), anyway you can customize them. Try the just uploaded build [here](https://github.com/ABuffEr/columnsReview/releases/download/20230226-dev/columnsReview-20230226-dev.nvda-addon), and close issue if everything works.

**Comment by ABuffEr** [comment]
Hi again,
sorry, there was a bug in previous build. Try [this one](https://github.com/ABuffEr/columnsReview/releases/download/20230226.01-dev/columnsReview-20230226.01-dev.nvda-addon) instead.

**Comment by Lo-lo78** [comment]
@ABuffEr 
It works perfectly.
The reproduction of the immediate veep is interesting.
A curiosity:
why does the veep sound three times and not twice?
The syntax for choosing frequencies and ms works very well.
👍

**Comment by Lo-lo78** [comment]
@ABuffEr 
If it's not too difficult we could insert a fourth value. The volume of the veep.
There may be users who prefer higher volume and other users prefer lower volume.
Thanks for what you are doing!

**Comment by ABuffEr** [comment]
> A curiosity: why does the veep sound three times and not twice?

It's not well documented at the moment, but I have considered three situations (even with voice):

1. you are at the list top;
2. you are in a list with only one item;
3. you are at the list bottom.

So, for the 2nd situation, I decided to generate a beep using absolute value of difference between top and bottom frequencies, and a doubled length.

**Comment by ABuffEr** [comment]
> If it's not too difficult we could insert a fourth value. The volume of the veep.

Not so easy, actually. This because beep function, I discovered after your comment, accepts left and right volume percentages, separately. And I don't like the solution to simply add one or two additional, common values in the edit fields, considering that, at this point, adding the possibility to have the top beep on the left and bottom left to the right would be better, I think.
So I have to do a lot of veeeery annoying GUI adjustmens, I'm afraid. This will take some time, be patient and keep opened this issue as reminder :)

**Comment by Lo-lo78** [comment]
@ABuffEr 
Ok!
I'm trying the veep and I'm very happy.
👍👍👍

**Comment by Lo-lo78** [comment]
@ABuffEr 
Is it possible to insert two wave samples chosen by the user, one List top and another List bottom?
Insert two buttons for the URL:
List top: browser... button
List bottom: browser... button
Obviously when you have time!
These are just practical suggestions. Veep is a possibility but if the user is willing to insert two .wav files it could be nice.
Do you prefer me to open another more specific issue?
Thank you!

**Comment by Lo-lo78** [comment]
@ABuffEr 
I am attaching two wav files.
[Samples.zip](https://github.com/ABuffEr/columnsReview/files/10895718/Samples.zip)

**Comment by ABuffEr** [comment]
> Do you prefer me to open another more specific issue? Thank you!

Yes, please. I'd appreciate also a sound for mono-item list, to provide a default (that user can remove if he wants, of course). Thanks for your support!

**Comment by Lo-lo78** [comment]
Hi Alberto,
Sorry for the wait but my father died and today I am completely without anyone.
I'm in Spain to solve bureaucratic problems.
I wanted to tell you that unfortunately I can't update this excellent add-on because there is no veep in the development versions. Is it a choice or haven't you considered it yet as an alternative to vocals?
Take care and big regards!
🤗

**Comment by ABuffEr** [comment]
Hi @Lo-lo78,
I not expanded the feature yet, but I not removed anything. Are you sure to update to last dev version, [here?](https://github.com/ABuffEr/columnsReview/releases/download/20230412-dev/columnsReview-20230412-dev.nvda-addon) Maybe add-on updater has suggested you the stable version, where beep is not present, if I remember well.

**Comment by Lo-lo78** [comment]
You are right.
Sorry!

**Comment by Lo-lo78** [comment]
@ABuffEr 
It seems to me that the issue can be closed.
Thanks Alberto!
