### ISSUE TITLE
When I read a column content or the position of an item in a list it is not possible to delete a file

### ISSUE THREAD

**Issue by Lo-lo78** [ABuffEr/columnsReview#28]
@ABuffEr 
When I use the addon and I'm in a folder listing I'm apparently in the right place but the system cursor loses focus and I have to use tab or shift+tab to get back to the listing.
It's an old problem.
As soon as I read a column or read the position of the item in a list I can no longer delete a file.
I have to tab or shift+tab to get the focus in the right place.
Greetings!

**Comment by ABuffEr** [comment]
> As soon as I read a column or read the position of the item in a list I can no longer delete a file. I have to tab or shift+tab to get the focus in the right place. Greetings!


Hi @Lo-lo78,
do you mean it happens always?
If yes, can you provide an exact steps-to-reproduce?
I have encountered the canc issue from time to time, but I had no particular reason to think it's caused by ColumnsReview. So, some questions:
- What version of Windows are you using?
- Are Ribbon menus disabled?
- Have you tried with ColumnsReview disabled?
- Do you have the empty folder announcement enabled?
- Does issue happen with Windows App Essentials disabled too?

**Comment by Lo-lo78** [comment]
If yes, can you provide an exact steps-to-reproduce?
I enter the folder and read a column. If I delete a file or folder there is no Windows warning to move the file or folder to the trash.
If I don't do any Columns Review operation the delete button works.
Also when I read how many items are in a folder it loses focus and you can't delete anything. You have to shift+tab or tab to bring the system cursor into the list.

do you mean it happens always?
Yes i've been wanting to point this out for a long time.

• What version of Windows are you using?
Windows 10 22H2 (AMD64) build 19045.2728

• Are Ribbon menus disabled?
No they are enabled

• Have you tried with ColumnsReview disabled?
Yes, I tried with the addon disabled.

• Do you have the empty folder announcement enabled?
Yes, I have enabled the ad.

• Does issue happen with Windows App Essentials disabled too?
Yes I just tried.


Greetings!

**Comment by Lo-lo78** [comment]
You found the problem.
It was the alt key. There is no problem with the windows key.
What do I do, close the issue?

**Comment by ABuffEr** [comment]
Oh yes, thanks! 😀

**Comment by Lo-lo78** [comment]
You should point it out in the readme that the alt key is not recommended for Windows Explorer.
Greetings!
