### ISSUE TITLE
moving in explorer becomes sluggish when using Columns Review 

### ISSUE THREAD

**Issue by vortex1024** [ABuffEr/columnsReview#30]
nvda 2023.1 portable, coluimns review 5.2.
When moving through list items in windows explorer, i get a 0.5 sec delay each time I press one of the arrows to move to a new item. When disabling columns review, the lag goes away.
the log does not show anything useful, not even in debug level.
thanks.

**Comment by ABuffEr** [comment]
Hi @vortex1024,
it's quite difficult to diagnose the situation. Some questions:
- what Windows are you using?
- does this happen with installed NVDA?
- do you have empty folder announcement enabled?
- do you have list bounds announcement enabled?
- are there improvements if you change any previous setting?
Thanks.

**Comment by vortex1024** [comment]
• what Windows are you using?
r: it happens on both 10 and 11. I don't have access to the 11 pc now, but the 10 exact version is Version 22H2 (OS Build 19045.2728).
• does this happen with installed NVDA?
r: on win 10,, yes 
• do you have empty folder announcement enabled?
no
• do you have list bounds announcement enabled?
no
• are there improvements if you change any previous setting?
no

**Comment by ABuffEr** [comment]
Hi @vortex1024,
can you try [this dev version](https://github.com/ABuffEr/columnsReview/releases/download/20230412-dev/columnsReview-20230412-dev.nvda-addon) and report if there are improvements?

**Comment by vortex1024** [comment]
Hi,
Still the same. I have tested with disabling empty folder announcements 
too.

------ Original Message ------
From: "Alberto Buffolino" ***@***.***>
To: "ABuffEr/columnsReview" ***@***.***>
Cc: "vortex1024" ***@***.***>; "Mention" 
***@***.***>
Sent: 15.04.2023 13:25:03
Subject: Re: [ABuffEr/columnsReview] moving in explorer becomes sluggish 
when using Columns Review (Issue #30)

**Comment by ABuffEr** [comment]
Ah, damn. I'll try to optimize other checks, but no guarantee.

**Comment by vortex1024** [comment]
hi Alberto,
Great! this seems to have fixsed the situation. this was the only thing preventing me to go to 2023.1, so these are very good news for me.\
Not sure what you mean by random recovery. DO you mean that it would have worked the official version now, too?

**Comment by ABuffEr** [comment]
Hi @vortex1024,
I mean that log could still say something like:

INFO - watchdog.waitForFreezeRecovery (14:54:40.206) - watchdog (11164):
Starting freeze recovery after 0.5000875999999153 seconds.
...
INFO - watchdog.waitForFreezeRecovery (14:54:40.458) - watchdog (11164):
Recovered from freeze after 0.7527256000000762 seconds.

but hopefully much much less frequently.
Anyway, keep on dev versions of the add-on until the next stable (of the add-on) :)
