### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by CyrilleB79** [ABuffEr/columnsReview#39]
Hi Alberto

Just tracking the need of a new release. Indeed, since the last release (5.3.0), new changes have been merged or need to be. Among them:
* 2024.x compatibility
* on-demand speech mode
* fix error logged when locking the computer
* probably new translations

Could you create a new release (and submit it to the Store)?

Grazie!

**Comment by ABuffEr** [comment]
Hi,
just done, also on [add-on store.](https://github.com/nvaccess/addon-datastore/issues/4598)

**Comment by CyrilleB79** [comment]
Many thanks!
