### ISSUE TITLE
Error in empty folder

### ISSUE THREAD

**Issue by CyrilleB79** [ABuffEr/columnsReview#40]
Hi Alberto

### STR
In Windows Explorer, enter an empty folder and use up/down arrows in it.

### Actual result
"0 items" is reported but an error is logged.

### Expected result
No error should be logged

### Log
```
ERROR - scriptHandler.executeScript (10:05:39.858) - MainThread (12304):
error executing script: <bound method CRList.script_reportEmpty of <NVDAObjects.Dynamic_CRList32RecognizableFileObjectVirtualContextMenuListListIAccessibleWindowNVDAObject object at 0x00A603F0>> with gesture 'flèche haut'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\columnsReview\globalPlugins\columnsReview\__init__.py", line 700, in script_reportEmpty
    self.reportEmpty()
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\columnsReview\globalPlugins\columnsReview\__init__.py", line 657, in reportEmpty
    if regions[-1].rawText != brlText:
       ~~~~~~~^^^^
IndexError: list index out of range
```

This happens when NVDA is started with no braille display connected. If a braille display is connected or even if it has been connected before, this does not occur.

### Versions
* Column review 5.4.0
* NVDA 2024.4.1
* Windows 10 22H2 (AMD64) build 19045.5011

**Comment by ABuffEr** [comment]
Hi Cyrille,
thanks. It should be fixed in new dev build, on add-on store too.
I'll wait some days to update the stable version.

**Comment by CyrilleB79** [comment]
OK thanks! All seems fine on my end.
